config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  post 'create_users' => 'welcome#create_users'

  get 'users' => 'welcome#users'

  post 'products' => 'welcome#create_products'

  get 'products' => 'welcome#products'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def create_users
  	User.create(name: params[:name], age: params[:age])

  	redirect_to users_path
  end

  def create_products
  	Product.create(product_params)
  	User.create(name: params[:name], age: params[:age])
  	redirect_to products_path
  end

  def index
  	@product = Product.new
  end

  def users
  	@users = User.all
  end

  def products
  	@products = Product.all
  end

  private
  def product_params
  		params.require(:product).permit(:name, :price, :quantity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NoScaffold</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Create a User</h1>

<%= form_with(url: create_users_path) do |f| %>
	<%= text_field_tag :name, nil, placeholder: "Your Name" %><br>
	<%= number_field_tag :age, nil, placeholder: "Your Age" %><br>
	<%= submit_tag "Create Profile" %>

<% end %>


<br>
<br>

<h3>Create a Product</h3>
<%= form_with(model: @product) do |f| %>
		<%= f.text_field :name, placeholder: "Name" %><br>
		<%= f.number_field :price, placeholder: "Price" %><br>
		<%= f.number_field :quantity, placeholder: "Quantity" %><br>
		<%= text_field_tag :name, nil, placeholder: "Your Name" %><br>
		<%= number_field_tag :age, nil, placeholder: "Your Age" %><br>
		<%= submit_tag "Create Product" %>
<% end %>

app/views/welcome/products.html.erb
<h1>Products</h1>

<table>
	<tr>
		<th>Name</th>
		<th>Price</th>
		<th>Quantity</th>
	</tr>
	<tbody>
		<% @products.each do |p| %>
			<tr>
				<td><%= p.name %>
				</td>
				<td><%= number_to_currency(p.price) %></td>
				<td><%= p.quantity %></td>
			</tr>
		<% end %>

	</tbody>
</table>

<%= link_to "Return to Index", root_path %>

app/views/welcome/users.html.erb
<h1>Users</h1>

<table>
	<tr>
		<th>Name</th>
		<th>Age</th>
	</tr>
	<tbody>
		<% @users.each do |user| %>
			<tr>
				<td><%= user.name %>
				</td>
				<td><%= user.age %></td>
			</tr>
		<% end %>

	</tbody>
</table>

<%= link_to "Return to Index", root_path %>